---

#
# Apache
#
- name: install apache
  yum: state=latest
  args:
    name: ['httpd', 'mod_ssl', 'openssl']
  tags: ['apache']

- name: Copy Apache config
  template: src=apache.conf.j2 dest=/etc/httpd/conf.d/jupyterhub.conf
             owner=root group=root mode=0644
  notify: restart apache
  tags: ['apache']

- name: Copy Apache lua authz config
  template: src=apache_lua_auth.lua.j2 dest=/etc/httpd/authz_usergroup.lua
             owner=root group=root mode=0644
  notify: restart apache
  tags: ['apache']

- name: apache mod_proxy
  apache2_module: name={{item}} state=present
  notify: restart apache
  with_items:
    - proxy
    - ssl
    - lua
  tags: ['apache']
#- name: apache mod_cgi disable
#  apache2_module: name=cgi state=absent
#  notify: restart apache

#- name: Apache listens on port 280 for dev server, too.
#  lineinfile:
#    path: '/etc/httpd/conf/httpd.conf'
#    regexp: '^Listen {{item}}'
#    line: 'Listen {{item}} http'
#    insertafter: '^Listen '
#  with_items:
#    - "80"
#    - "280"
#  notify: restart apache
#  tags: ['apache']

- name: Apache set mpm=worker (for shibboleth)
  template: src=apache.mpm.conf.j2 dest=/etc/httpd/conf.modules.d/00-mpm.conf
             owner=root group=root mode=0644
  notify: restart apache
  tags: ['apache']

- name: enable apache
  service: name=httpd enabled=yes state=started enabled=yes daemon_reload=yes
  notify: restart apache
  tags: ['apache']

#
# Sudo
#
- name: Copy sudoers rule
  template: src=sudoers.j2 dest=/etc/sudoers.d/jupyterhub-daemon
             owner=root group=root mode=0440
  tags: ['jhub']

# create jupyterhub-daemon user  # - done on install2


#
# Jupyterhub config
#
- name: make /etc/jupyterhub
  file: path=/etc/jupyterhub state=directory group=jupyterhub-daemon owner=jupyterhub-daemon mode=u=rwx,g=rwx,o=
  tags: ['jhub']
- name: create cookie secret
  shell: "umask 0337 ; openssl rand -hex 32 > /etc/jupyterhub/jupyterhub_cookie_secret ; chown jupyterhub-daemon /etc/jupyterhub/jupyterhub_cookie_secret"
  args:
    creates: /etc/jupyterhub/jupyterhub_cookie_secret
  tags: ['jhub']
- name: make configurable-http-proxy auth token
  shell: "umask 0337 ; echo \"CONFIGPROXY_AUTH_TOKEN=`openssl rand -hex 32`\" > /etc/jupyterhub/configurable-http-proxy-token.var ; chown jupyterhub-daemon /etc/jupyterhub/configurable-http-proxy-token.var"
  args:
    creates: /etc/jupyterhub/configurable-http-proxy-token.var
  tags: ['jhub-chp']

#
# Jupyterhub daemonization
#
- name: Copy systemd jhub-chp.service
  template: src=systemd.chp.j2 dest=/etc/systemd/system/jhub-chp.service
             owner=root group=root mode=0440
  notify: restart jhub-chp
  tags: ['jhub-chp']

- name: Copy systemd jupyterhub.service
  template: src=systemd.j2 dest=/etc/systemd/system/jupyterhub.service
             owner=root group=root mode=0440
  notify: restart jupyterhub
  tags: ['jhub']

- name: Create systemd persistent log directory
  file: path=/var/log/journal state=directory mode=770
  #notify: restart systemd
  tags: ['jhub']

- name: Start systemd service
  systemd: name=jupyterhub.service state=started enabled=yes daemon_reload=yes
  tags: ['jhub']

- name: Start systemd service
  systemd: name=jhub-chp.service state=started enabled=yes daemon_reload=yes
  tags: ['jhub-chp']


#
# Shibboleth
#
# https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPLinuxRPMInstall
- name: Shib install shibboleth
  yum: name={{item}} state=latest
  with_items:
    - shibboleth.x86_64
  tags: ['shib']
  notify: restart shib

# copy over shib keys
# chown shib keys to user shibd
#   chgrp -R shibd /etc/ssl/private/shib/
#   chmod -R g+rX /etc/ssl/private/shib/

- name: Shib copy over HAKA root CA
  copy: src={{shib_metadata_signature}} dest=/etc/shibboleth/
  tags: ['shib']

- name: Shib install root CRL once
  shell: "cd /etc/shibboleth/ && wget -N http://crl.tcs.terena.org/TERENASSLCA.crl"
  args:
    creates: /etc/shibboleth/TERENASSLCA.crl
  tags: ['shib']
  notify: restart shib

- name: Shib install cron job to update root CRL
  template: src=shib.cron.update-crl.j2 dest=/etc/cron.d/shib.cron.update-crl
             owner=root group=root mode=0444
  tags: ['shib']
  notify: restart shib

- name: Shib cron job to update root CRL
  template: src={{item}}.j2 dest=/etc/shibboleth/{{item}}
             owner=root group=root mode=0644
  with_items:
    - shibboleth2.xml
    - attribute-map.xml
    - attribute-policy.xml
  tags: ['shib']
  notify: restart shib

- name: Shib Start systemd service
  systemd: name=shibd state=started enabled=yes daemon_reload=yes
  tags: ['shib']
